### ISSUE TITLE
Suggestion to Fab Lab Barcelona image 

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/mdef-docs#18]
https://github.com/fablabbcn/mdef-docs/blob/43f2c5297d4a4bf532b339c4e69c403e8446063f/custom_theme/home.html#L216

I suggest looking for an image that differentiates from the IAAC one and shows some activities more related to our work. I recommend looking at our Flick and this album  in particular 

https://www.flickr.com/photos/fablabbarcelona/albums/72177720300812583/with/53038892193

**Comment by peters-rebecca** [comment]
Updated!
