### ISSUE TITLE
Landing becomes unresponsive

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/mdef-docs#21]
During presentations, sometimes the landing page becomes unresponsive and in some cases a Chrome warning appears. Unfortunately, we haven't had time to document it properly as a quick refresh has always solved the issue. 

However, it would be helpful to investigate the JS running in the landing page to detect any possible bugs and avoid this issue in the future.

**Comment by peters-rebecca** [comment]
Solved in  #25
