### ISSUE TITLE
Glossary Section

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/mdef-docs#6]
Preliminary Content
=============

Futures Scouting: It relates to research in the present, through indicators and past experiences, to imagine and develop future scenarios that could become.

New-normals: A new normal is a previously unfamiliar situation that, for different reasons, has become common in the present.

Weak Signals: Early indicators of change that have the potential to trigger major events in the future.

Drivers: external sociological forces that have led to its creation (a recession, a growing need to re-evaluate our sense of community,...)

Self-Reflexivity: denotes both self reflection and introspection, being aware of one’s own subjectivity, and its influence on a specific situation.

Reflective practitioner: It describes the practice of a designer shifting positions though the design process, and asking “what if?” to recognise implications from his/her ongoing exploration (Schon, D. A. (1983). 

*The reflective practitioner: how professionals think in action*. New York: Basic Books. ISBN 978-0465068746).

Co-shaping: Co-shaping relates to how technology transforms human relations and at same time human relations transform technology (Verbeek, P. P. (2006). 

Materializing morality: Design ethics and technological mediation. *Science, Technology, & Human Values*, *31*(3), 361-380).

Socio-technical systems: "Socio-cultural" and "technical" systems together create our socio-technical environment. Within these networks, technology and society coexist in an intertwined, hybrid form.

1st, 2nd and 3rd person perspective: There are different approaches to relate to the socio-technical system object of study. 3rd person perspective relates to gathering information without getting involved, and *a* 2nd person perspective is about designing with a sample of the target group. In a 1st person perspective, the designer is part of a system within the existing social structures. 

Positionality: How do I make sense of things? From my position, what tactic will be empowering? Transparency? Being opaque and deliberately confusing?

Boundaries: Situational aspect in relation to the community. It is a shared notion. How can "we" speculate? (question who is "we"?).  What could we do? What other things can be done? What are the other possibilities? What propositions can we offer?

Networks: Quality of relationships between actors. How can these different positions co-exist and be generative of new collaborative 'we' discussions?

Autoethnography: understood as a qualitative research method aims to describe and systematically analyze personal experience to understand cultural context.

Autobiographical design: The designer uses his or her own experience and position as part of its design research as data input. (Neustaedter, C. and Sengers, P. (2012) Autobiographical design: what you can learn from designing for yourself. interactions 19, 6 (November + December 2012), 28–33. DOI:https://doi.org/10.1145/2377783.2377791).

Alternative present: Alternative presents give designers the key to opening escape routes to the present continuities, offering space to radically imagine discontinuities that would offer different outcomes in favor of more optimistic future scenarios than the ones we are being presented as the most plausible results of our current business-as-usual practices. 

Design intervention: The action of deploying prototypes (physical, digital, ideas, methodologies) in the real world in order to explore and trigger actions in humans and non-humans.

Design space:  A physical or digital collection of experiments, reference objects, projects, products or materials visualised in a 2d-form in a meaningful way. It can integrate prototypes and projects developed previously, as well as other forms of information. 

Ways of Drifting: Drifting refers to the process of finding alternative design opportunities for one’s work through feeling, sensing, embodying and making.

Design Biographies: The designers’ collection of design objects and the marks they leave in the world (Wakkary, R. (2021). Things We Could Design. MIT Press). 

Situated practices: practices that are situated in a particular and local position, relative to what is known and to other practices (drawn from Haraway 1988). Haraway’s (1988) ‘Situated Knowledges’

**Comment by peters-rebecca** [comment]
@pral2a (https://mdef.fablabbcn.org/glossary/) Dime si te parece bien y la pongo en el menú principal.

**Comment by pral2a** [comment]
Great! I will suggest adding an Admonitions with a text similar to this one:

"Every emerging field brings forth a unique lexicon and set of definitions, underscoring the vital need for an open-contributed glossary to facilitate effective communication and collaboration within the program."

**Comment by peters-rebecca** [comment]
I think this is closed. Reopen if needed.
